# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lC8OZ9epdLjuvBWKSp1zye-iUJZQxhqU

Дана функция f(x) = 5x^2 + 10x - 30

Определить корни

Найти интервалы, на которых функция возрастает

Найти интервалы, на которых функция убывает

Построить график

Вычислить вершину

Определить промежутки, на котором f > 0

Определить промежутки, на котором f < 0
"""

import matplotlib.pyplot as plt
import random
import numpy as np

f = lambda x: random.randint(1, 10)

points = list(map(f, range(1, 10)))

plt.plot(points, 'b-')

a, b, c = 5, 10, -30

x = np.arange(-10, 10, 0.01)

def func(a, b, c, x):
    return a * x ** 2 + b * x + c

def disc(a, b, c):
    return b **2 - 4 * a * c

print(disc(a, b, c))

def find_sqrt(a, b, c):
    d = disc(a, b, c)
    if d < 0:
        return ('Корней нет',)
    elif d == 0:
        x = -b / (2 * a)
        return (round(x, 2),)
    else:
        x1 = (-b + d ** 0.5) / (2 * a)
        x2 = (-b - d ** 0.5) / (2 * a)
        return (round(x1, 2), round(x2, 2),)

sqrt = find_sqrt(a, b, c)

min_y = min(func(a, b, c, x))

print(min_y)

c2 = c - min_y
min_x = find_sqrt(a, b, c2)
min_x = min_x[0]
print('Вершина графика: ', min_x, min_y)

grow_up_x = np.arange(min_x, 10, 0.01)
grow_down_x = np.arange(-10, min_x, 0.01)

pos_down = np.arange(-10, sqrt[1], 0.01)
neg_down = np.arange(sqrt[1], min_x, 0.01)
neg_up = np.arange(min_x, sqrt[0], 0.01)
pos_up = np.arange(sqrt[0], 10, 0.01)

# plt.plot(x, func(a, b, c, x), 'r-')

#корни
plt.plot(sqrt[0], 0, 'go', label = f'Корни ({sqrt[0]}, {sqrt[1]})')
plt.plot(sqrt[1], 0, 'go')

#вершина
plt.plot(min_x, min_y, 'rx', label = f'Вершина({min_x}, {min_y})')

#возрастание графика
# plt.plot(grow_up_x, func(a, b, c, grow_up_x), 'y-')

#убывание графика
# plt.plot(grow_down_x, func(a, b, c, grow_down_x), 'b-')

#pos_down
plt.rcParams['lines.linestyle'] = '-'
plt.plot(pos_down, func(a, b, c, pos_down), 'b', label = 'Убывает > 0')

#neg_down
plt.rcParams['lines.linestyle'] = '-.'
plt.plot(neg_down, func(a, b, c, neg_down), 'b', label = 'Убывает < 0')

#neg_up
plt.rcParams['lines.linestyle'] = '-.'
plt.plot(neg_up, func(a, b, c, neg_up), 'y', label = 'Возрастает < 0')

#pos_up
plt.rcParams['lines.linestyle'] = '-'
plt.plot(pos_up, func(a, b, c, pos_up), 'y', label = 'Возрастает > 0')
plt.legend()
plt.grid()